export const GET_ALL_ORDER_LISTEN = "ClientOrders/GET_ALL_ORDER_LISTEN"
export const GET_ALL_ORDER_SUCCESS = "ClientOrders/GET_ALL_ORDER_SUCCESS"

export const HANDLE_GET_ALL_ORDER_LOADER = "ClientOrders/HANDLE_GET_ALL_ORDER_LOADER"

export const GET_ORDER_BY_ID_LISTEN = "ClientOrders/GET_ALL_ORDER_BY_ID_LISTEN"
export const GET_ORDER_BY_ID_SUCCESS = "ClientOrders/GET_ALL_ORDER_BY_ID_SUCCESS"

export const HANDLE_GET_ORDER_BY_ID_LOADER = "ClientOrders/HANDLE_GET_ORDER_BY_ID_LOADER"