export const GET_ALL_ORDER_LISTEN = "ClientOrders/GET_ALL_ORDER_LISTEN"
export const GET_ALL_ORDER_SUCCESS = "ClientOrders/GET_ALL_ORDER_SUCCESS"

export const HANDLE_GET_ALL_ORDER_LOADER = "ClientOrders/HANDLE_GET_ALL_ORDER_LOADER"

export const GET_ORDER_BY_ID_LISTEN = "ClientOrders/GET_ALL_ORDER_BY_ID_LISTEN"
export const GET_ORDER_BY_ID_SUCCESS = "ClientOrders/GET_ALL_ORDER_BY_ID_SUCCESS"

export const HANDLE_GET_ORDER_BY_ID_LOADER = "ClientOrders/HANDLE_GET_ORDER_BY_ID_LOADER"

export const GET_ORDER_TIME_LINE_LISTEN = "Orders/GET_ORDER_TIME_LINE_LISTEN"
export const GET_ORDER_TIME_LINE_SUCCESS = "Orders/GET_ORDER_TIME_LINE_SUCCESS"

export const HANDLE_ORDER_TIME_LINE_LOADER  = "Orders/HANDLE_ORDER_TIME_LINE_LOADER"