export const GET_SUB_SERVICES_LISTEN = "MainService/GET_SUB_SERVICES_LISTEN"
export const GET_SUB_SERVICE_SUCCESS = "MainService/GET_SUB_SERVICE_SUCCESS"

export const GET_MAIN_SERVICE_BY_ID_LISTEN = "MainService/GET_MAIN_SERVICE_BY_ID_LISTEN"
export const GET_MAIN_SERVICE_BY_ID_SUCCESS = "MainService/GET_MAIN_SERVICE_BY_ID_SUCCESS"

export const HANDLE_GET_MAIN_SERVICE_BY_ID_LOADER = "MainService/HANDLE_GET_MAIN_SERVICE_BY_ID_LOADER"

export const GET_SUB_SERVICE_BY_ID_LISTEN = "MainService/GET_SUB_SERVICE_BY_ID_LISTEN"
export const GET_SUB_SERVICE_BY_ID_SUCCESS = "MainService/GET_SUB_SERVICE_BY_ID_SUCCESS"