export const SCREEN_INDEX_SET = "Signup/SCREEN_INDEX_SET"

export const GET_ALL_COUNTRIES_LISTEN = "Signup/GET_ALL_COUNTRIES_LISTEN"
export const GET_ALL_COUNTRIES_SUCCESS = "Signup/GET_ALL_COUNTRIES_SUCCESS"