export const SCREEN_INDEX_SET = "Signup/SCREEN_INDEX_SET"

export const GET_ALL_COUNTRIES_LISTEN = "Signup/GET_ALL_COUNTRIES_LISTEN"
export const GET_ALL_COUNTRIES_SUCCESS = "Signup/GET_ALL_COUNTRIES_SUCCESS"

export const SIGNUP_LISTEN = "Signup/SIGNUP_LISTEN"
export const SIGNUP_SUCCESS = "Signup/SIGNUP_SUCCESS"
export const SIGNUP_FAILED = "Signup/SIGNUP_FAILED"

export const STORE_DATA_LISTEN = "Signup/STORE_DATA_LISTEN"
export const STORE_DATA_SUCCESS = "Signup/STORE_DATA_SUCCESS"
export const STORE_DATA_FAILED = "Signup/STORE_DATA_FAILED"

export const SEND_OTP_LISTEN = "Signup/SEND_OTP_LISTEN"
export const SEND_OTP_SUCCESS = "Signup/SEND_OTP_SUCCESS"
export const SEND_OTP_FAILED = "Signup/SEND_OTP_FAILED"

export const SIGNUP_LOADING_START = "Signup/SIGNUP_LOADING_START"
export const SIGNUP_LOADING_END = "Signup/SIGNUP_LOADING_END"

export const VERIFY_LOADING_START = "Signup/VERIFY_LOADING_START"
export const VERIFY_LOADING_END = "Signup/VERIFY_LOADING_END"

export const LOGIN_LISTEN = "Signup/LOGIN_LISTEN"
export const LOGIN_SUCCESS = "Signup/LOGIN_SUCCESS"

export const SIGNOUT_LISTEN = "Signup/SIGNOUT_LISTEN"
export const SIGNOUT_SUCCESS = "Signup/SIGNOUT_SUCCESS"

export const USER_DATA_ADD_LISTEN = "Signup/USER_DATA_ADD_LISTEN"