export const LOGIN_LISTEN = "login/LOGIN_LISTEN"
export const LOGIN_SUCCESS = "login/LOGIN_SUCCESS"

export const GET_CURRENT_USER_LISTEN = "Login/GET_CURRENT_USER_LISTEN"
export const GET_CURRENT_USER_SUCCESS = "Login/GET_CURRENT_USER_SUCCESS"

export const GET_ALL_MAIN_SERVICES_LISTEN = "Login/GET_ALL_MAIN_SERVICES_LISTEN"
export const GET_ALL_MAIN_SERVICES_SUCCESS = "Login/GET_ALL_MAIN_SERVICES_SUCCESS"