export const LOGIN_LISTEN = "login/LOGIN_LISTEN"
export const LOGIN_SUCCESS = "login/LOGIN_SUCCESS"

export const GET_CURRENT_USER_LISTEN = "Login/GET_CURRENT_USER_LISTEN"
export const GET_CURRENT_USER_SUCCESS = "Login/GET_CURRENT_USER_SUCCESS"