export const HANDLE_ORDER_LOADER_LISTEN = "Orders/HANDLE_ORDER_LOADER_LISTEN"

export const HANDLE_ORDER_STATE = "Orders/HANDLE_ORDER_STATE"

export const GET_ORDER_BY_ID_LISTEN = "Orders/GET_ORDER_BY_ID_LISTEN"
export const GET_ORDER_BY_ID_SUCCESS = "Orders/GET_ORDER_BY_ID_SUCCESS"

export const HANDLE_GET_ORDER_BY_ID_LOADER = "Orders/HANDLE_GET_ORDER_BY_ID_LOADER"

export const GET_ORDER_SOURCE_FILES_LISTEN = "Orders/GET_ORDER_SOURCE_FILES_LISTEN"
export const GET_ORDER_SOURCE_FILES_SUCCESS = "Orders/GET_ORDER_SOURCE_FILES_SUCCESS"

export const HANDLE_GET_ORDER_SOURCE_FILES_LOADER = "Orders/HANDLE_GET_ORDER_SOURCE_FILES_LOADER"