export const SET_SCREEN_INDEX = "clientProfile/SET_SCREEN_INDEX"

export const PROFILE_UPDATE_LISTEN = "clientProfile/PROFILE_UPDATE_LISTEN"
export const PROFILE_UPDATE_SUCCESS = "clientProfile/PROFILE_UPDATE_SUCCESS"

export const PROFILE_IMG_UPDATE_LISTEN = "clientProfile/PROFILE_IMG_UPDATE_LISTEN"
export const PROFILE_IMG_UPDATE_SUCCESS = "clientProfile/PROFILE_IMG_UPDATE_SUCCESS"

export const COVER_IMG_UPDATE_LISTEN = "clientProfile/COVER_IMG_UPDATE_LISTEN"
export const COVER_IMG_UPDATE_SUCCESS = "clientProfile/COVER_IMG_UPDATE_SUCCESS"

export const IMAGE_UPLOAD_PROGRESS_LISTEN = "clientProfile/IMAGE_UPLOAD_LISTEN"

export const GET_ALL_ORDERS_BY_CUSTOMER_LISTEN = "clientProfile/GET_ALL_ORDERS_BY_CUSTOMER_LISTEN"
export const GET_ALL_ORDERS_BY_CUSTOMER_SUCCESS = "clientProfile/GET_ALL_ORDERS_BY_CUSTOMER_SUCCESS"

export const GET_CUSTOMER_ORDER_BY_ID_LISTEN = "clientProfile/GET_CUSTOMER_ORDER_BY_ID_LISTEN"
export const GET_CUSTOMER_ORDER_BY_ID_SUCCESS = "clientProfile/GET_CUSTOMER_ORDER_BY_ID_SUCCESS"

export const HANDLE_GET_ALL_ORDERS_BY_CUSTOMER_LOADER = "clientProfile/HANDLE_GET_ALL_ORDERS_BY_CUSTOMER_LOADER"
export const HANDLE_GET_CUSTOMER_ORDER_BY_ID_LOADER = "clientProfile/HANDLE_GET_CUSTOMER_ORDER_BY_ID_LOADER"