export const SET_SCREEN_INDEX = "clientProfile/SET_SCREEN_INDEX"

export const PROFILE_UPDATE_LISTEN = "clientProfile/PROFILE_UPDATE_LISTEN"
export const PROFILE_UPDATE_SUCCESS = "clientProfile/PROFILE_UPDATE_SUCCESS"

export const PROFILE_IMG_UPDATE_LISTEN = "clientProfile/PROFILE_IMG_UPDATE_LISTEN"
export const PROFILE_IMG_UPDATE_SUCCESS = "clientProfile/PROFILE_IMG_UPDATE_SUCCESS"

export const COVER_IMG_UPDATE_LISTEN = "clientProfile/COVER_IMG_UPDATE_LISTEN"
export const COVER_IMG_UPDATE_SUCCESS = "clientProfile/COVER_IMG_UPDATE_SUCCESS"